sudo: required
language: ruby
services:
  - docker
install: true
before_script:
  - TAG=${TRAVIS_TAG:-0.0.0}
  - VERSION=${TAG%.*}
  - RELEASE=${TAG##*.}
  - RELEASE=${RELEASE:-0}
script:
  - docker build -t chipin/configure-rpm .
  - mkdir -p /tmp/RPMS/x86_64
  - sudo chown 111:111 -R /tmp/RPMS
  - docker run -it --rm --name configure-rpm -v /tmp/RPMS:/home/builder/rpmbuild/RPMS chipin/configure-rpm /usr/bin/rpmbuild -bb -D "CHIP_IN_RELEASE $RELEASE" -D "CHIP_IN_VERSION $VERSION" rpmbuild/SPECS/configure.spec
  - (cd /tmp;tar -czf - RPMS) > $TRAVIS_BUILD_DIR/configure-rpm.tar.gz
before_deploy:
  - TRAVIS_TAG=$VERSION
deploy:
  provider: releases
  api_key:
    secure: PeWzJRj4uo+7A2g8HlSF3RTUau7IEZpwQzQw3ZHFitm2XRt6E7inFgrrTj4/umt6HVuvjXv3dYRFeW7lFzliUlPq2WqRuCGVXzgLlTKgHFwiMWyWS0p12S6MZqgufb6ril5DftEvaJ8fuZU2iP4zDDkjBy5jwCGbx0rl+saZrAR7AtdF0PZs8n0hVQN4UO56p7zJGe+Fs5v9xMgZzy4MDP7aCR9woixH83u5on/VxYTzmtzNjMRYCU94nGfJ0sbfzZsx6v5FWYVZzWLWtCAE54po+kyAyeY8S4cLHTvVMm6x+ch7sMyctiHJuAuEupZWOcOwziqiaymogJM4wLP0hL0rY1Tc+f2DtOAuDGJ+SDY9Y886aF2Or95svav0pgBTLtWtcVBSVHuaMJIytdfQ/G8W8lxCaXM8FutUvjinV/jt5pgjozxQi9l9xbO9L+2iKPYmwjDKFrSGyzdJJU/7WnVPqlN8PUj1XJ30VYyzab0N4ErErV57C2L7jGosl7j7JteWuJewq7TL6QPmL9btXjXMidaI7gMRo+y9wkVAfVp3nkFaKJZkhbb57IRb/0xR3CbaFqCfZOsBxbryccLFF8HirDfKSOEwxQYOsYWvwVjvAw/iIWXa9F90nG13GrxBRbaqzbqKu9aBNssbkEhBOmjGFLYS1PeUu3GQYZVote4=
  file: configure-rpm.tar.gz
  overwrite: true
  skip_cleanup: true
  on:
    repo: chip-in/configure
    tags: true
