#!/bin/bash
# CAUTION: Do not edit this file.
# this script is generated by consul-template

LOGGER=$(basename -s .sh $0)

function message () {
  echo "INFO: $LOGGER:" $*
}

function error () {
  echo "ERROR: $LOGGER:" $* 1>&2
  exit 1
}

function reloadNginx() {
  message "Trigger reload nginx."
  systemctl reload nginx
}

function reloadShibboleth() {
  message "Trigger restart shibboleth."
  systemctl estart shibd shibfcgi
}

function upload() {
  local target=$1
  local service=$2
  local workfile=$WORKDIR/$(basename $target)
  /usr/bin/cat > $workfile
  if ! /usr/bin/cmp -s $target $workfile; then
    mkdir -p $(dirname $target)
    /usr/bin/mv $workfile $target
    if [ $service == nginx ]; then
      NEED_RELOAD_NGINX=true
    elif [ $service == shibboleth ]; then
      NEED_RELOAD_SHIBBOLETH=true
    fi
  fi
}

function cleanup() {
  local target=$1
  local service=$2
  if [ -f $target ]; then
    /usr/bin/rm $target
    if [ $service == nginx ]; then
      NEED_RELOAD_NGINX=true
    elif [ $service == shibboleth ]; then
      NEED_RELOAD_SHIBBOLETH=true
    fi
  fi
}
