name: release apps

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  push_to_github:
    name: Release artifacts to github
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env
        run: echo "TAG_VALUE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kkuwa'

      - name: bundle
        env:
          WORK_DIR: ${{ github.workspace }}
        run: |
          VERSION=$(node -e "var fs = require('fs');console.log(JSON.parse(fs.readFileSync('composer.json').toString('utf-8')).version);")
          RELEASE=1
          docker build -t chipin/configure-rpm .
          mkdir -p /tmp/RPMS/x86_64
          sudo chown 111:111 -R /tmp/RPMS
          docker run --rm --name configure-rpm -v /tmp/RPMS:/home/builder/rpmbuild/RPMS chipin/configure-rpm /usr/bin/rpmbuild -bb -D "CHIP_IN_RELEASE $RELEASE" -D "CHIP_IN_VERSION $VERSION" rpmbuild/SPECS/configure.spec
          (cd /tmp;tar -czf - RPMS) > $WORK_DIR/configure-rpm.tar.gz

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: configure-rpm.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{env.TAG_VALUE}}"
          allowUpdates: true
